import "./globals.css";
import { Inter } from "next/font/google";
import SessionProvider from "@/components/NextAuthProvider";
const inter = Inter({ subsets: ["latin"] });
import NextAuthProvider from "@/components/NextAuthProvider";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({
  children,
  session
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
